### ISSUE TITLE
Allow :whitespace: as separator

### ISSUE THREAD

**Issue by m4dz** [adrianlee44/atom-aligner#47]
Hi!

I'm used to work with [Stylus](http://stylus-lang.com/) files, and it allows to forgot `:` when declaring properties (http://stylus-lang.com/docs/selectors.html), so:

```stylus
body
    background-color #333
    color white
```

will be compiled to:

```css
body {
    background-color: #333;
    color: white;
}
```

I want / need to align my CSS properties in this form:

```stylus
body
    background-color #333
    color            white
```

Can we use a dedicated separator like *first whitespace available* to make alignment? Is this possible only with a provider, or do we need to hack the aligner core to do this? I can develop it, but I need some first tips to start :wink:.

Thanks!

**Comment by adrianlee44** [comment]
Hi @m4dz,
I used to work with Stylus too and remember those whitespaces. Whitespaces is a little tricky. Let me double check the stylus grammar. Most like a new provider and some core code changes will be needed.

**Comment by m4dz** [comment]
Oops, I missed your reply, so sorry :sweat:
Tell me if I can help you in any way. Thanks a lot for your work!

**Comment by adrianlee44** [comment]
I have finally gotten around to look deeper into this issue. With the release of v0.21.0, aligner now support whitespace as separator.

You will have to install https://atom.io/packages/aligner-stylus to align whitespace correctly though.

Since Aligner relies on the grammar to work properly, I have tested this against https://atom.io/packages/stylus. Let me know if you are using other packages and it's not working with those.

**Comment by m4dz** [comment]
Woohooo, you're awesome :tada:! Thanks :+1: !
